CREATE TABLE "onboarding_case" (
  "id" BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
  "workflow_id" RAW(16) NOT NULL,
  "branch_name" VARCHAR(20) NOT NULL,
  "request_type" VARCHAR(20) NOT NULL,
  "first_name" VARCHAR(50),
  "last_name" VARCHAR(50),
  "salutation" VARCHAR(20),
  "date_of_birth" DATE,
  "bsn" VARCHAR(9),
  "street" VARCHAR(100),
  "house_number" VARCHAR(20),
  "city" VARCHAR(100),
  "province" VARCHAR(100),
  "country" VARCHAR(50),
  "mobile_phone" VARCHAR(15),
  "home_phone" VARCHAR(15),
  "whatsapp" VARCHAR(15),
  "email" VARCHAR(255),
  "screening_required" NUMBER(1) DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id")
);
