CREATE TABLE "task" (
  "id" BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
  "case_id" BIGINT NOT NULL,
  "task_type" VARCHAR(20) NOT NULL,
  "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  "completed_at" TIMESTAMP WITHOUT TIME ZONE,
  "priority" VARCHAR(10) NOT NULL DEFAULT 'NORMAL',
  PRIMARY KEY ("id")
);
